apiVersion: v1
kind: Pod
metadata:
  name: prometheus
  namespace: default
spec:
  containers:
  - name: prometheus
    image: prom/prometheus
    resources:
      limits:
        cpu: 100m
        memory: 256M
    args: ['-config.file=/etc/prometheus/prometheus.yml',
            '-alertmanager.url=http://127.0.0.1:9093',
            '-storage.local.path=/data/prometheus']
    volumeMounts:
    - name: etc
      mountPath: /etc/prometheus
    - name: data
      mountPath: /data/prometheus
    ports:
    - containerPort: 9090
      hostPort: 9090
  - name: alertmanager
    image: prom/alertmanager
    resources:
      limits:
        cpu: 100m
        memory: 100M
    args: ['-config.file=/etc/prometheus/alertmanager.conf',
            '-notification.smtp.smarthost=',
            '-notification.smtp.sender=']
    env:
    - name: SMTP_AUTH_USERNAME
      value: 
    - name: SMTP_AUTH_PASSWORD
      value: 
    volumeMounts:
    - name: etc
      mountPath: /etc/prometheus
    ports:
    - containerPort: 9093
  volumes:
  - name: etc
    hostPath:
      path: /data/prometheus/etc
  - name: data
    hostPath:
      path: /data/prometheus/data
